### ISSUE TITLE
Race condition?

### ISSUE THREAD

**Issue by ljnelson** [microbean/microbean-helidon-webserver-cdi#1]
The `TestBasicScenario` test fails every now and again.  Some changes I'm making locally added just enough delay somewhere in the mechanism to make this reproducible one time out of about three.

Sample output and stack trace:
```
INFO] Running org.microbean.helidon.webserver.cdi.TestBasicScenario
Jan 11, 2019 1:14:51 PM org.jboss.weld.bootstrap.WeldStartup <clinit>
INFO: WELD-000900: 3.0.5 (Final)
Jan 11, 2019 1:14:51 PM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 6.0.13.Final
Jan 11, 2019 1:14:52 PM org.jboss.weld.environment.deployment.discovery.DiscoveryStrategyFactory create
INFO: WELD-ENV-000020: Using jandex for bean discovery
Jan 11, 2019 1:14:52 PM org.jboss.weld.bootstrap.MissingDependenciesRegistry handleResourceLoadingException
INFO: WELD-000119: Not generating any bean definitions from org.microbean.jpa.org.hibernate.engine.transaction.jta.platform.CDISEJtaPlatform because of underlying class loading error: Type org.hibernate.engine.transaction.jta.platform.internal.AbstractJtaPlatform not found.  If this is unexpected, enable DEBUG logging to see the full error.
Jan 11, 2019 1:14:53 PM org.jboss.weld.environment.se.WeldContainer fireContainerInitializedEvent
INFO: WELD-ENV-002003: Weld SE container bc9317d1-3d3a-4a82-91e9-14e284244ccc initialized
*** HelidonWebServerExtension onStartup fired
*** initializing serviceBean
[EL Info]: 2019-01-11 13:14:54.054--ServerSession(2066366456)--EclipseLink, version: Eclipse Persistence Services - 2.7.2.v20180622-f627448
Jan 11, 2019 1:14:54 PM com.zaxxer.hikari.HikariDataSource <init>
INFO: test - Starting...
Jan 11, 2019 1:14:54 PM com.zaxxer.hikari.HikariDataSource <init>
INFO: test - Start completed.
[EL Info]: 2019-01-11 13:14:54.381--ServerSession(2066366456)--/file:/Users/LANELSON/Projects/github/microbean/microbean-helidon-webserver-cdi/target/_test login successful
[EL Warning]: 2019-01-11 13:14:54.417--The collection of metamodel types is empty. Model classes may not have been found during entity search for Java SE and some Java EE container managed persistence units.  Please verify that your entity classes are referenced in persistence.xml using either <class> elements or a global <exclude-unlisted-classes>false</exclude-unlisted-classes> element
*** serviceBean initialized
Jan 11, 2019 1:14:55 PM io.netty.util.internal.logging.Slf4JLogger info
INFO: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
*** test onStartup fired
Jan 11, 2019 1:14:55 PM io.helidon.webserver.netty.NettyWebServer lambda$start$7
INFO: Channel '@default' started: [id: 0xe2d7a600, L:/0:0:0:0:0:0:0:0:50290]
Jan 11, 2019 1:14:55 PM io.helidon.webserver.netty.NettyWebServer lambda$start$5
INFO: Channel '@default' closed: [id: 0xe2d7a600, L:/0:0:0:0:0:0:0:0:50290]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.839 s <<< FAILURE! - in org.microbean.helidon.webserver.cdi.TestBasicScenario
[ERROR] test(org.microbean.helidon.webserver.cdi.TestBasicScenario)  Time elapsed: 3.796 s  <<< ERROR!
javax.enterprise.event.ObserverException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.jboss.weld.security.NewInstanceAction.run(NewInstanceAction.java:33)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:40)
	at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:78)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:103)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
	at org.jboss.weld.injection.MethodInvocationStrategy$DefaultMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:109)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
	at org.jboss.weld.util.Observers.notify(Observers.java:166)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:159)
	at org.jboss.weld.manager.BeanManagerImpl.fireEvent(BeanManagerImpl.java:632)
	at org.jboss.weld.environment.se.WeldContainer.fireContainerInitializedEvent(WeldContainer.java:236)
	at org.jboss.weld.environment.se.WeldContainer.endInitialization(WeldContainer.java:188)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:803)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:176)
	at org.microbean.helidon.webserver.cdi.TestBasicScenario.startCdiContainer(TestBasicScenario.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.io.FileNotFoundException: http://0.0.0.0:50290/hoopy
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.URLConnection.getContent(URLConnection.java:739)
	at java.net.URL.getContent(URL.java:1059)
	at org.microbean.helidon.webserver.cdi.TestBasicScenario.onStartup(TestBasicScenario.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
	... 43 more
```

This test deliberately brings in a couple of other extensions but is reflective of real-world usage.

**Comment by ljnelson** [comment]
This is very interesting.  It's not a race condition.

It appears that if you create a `Set` of annotation literals consisting of `Any.Literal.INSTANCE` and `Default.Literal.INSTANCE`, then calling `beanManager.getBeans(SomeType.class, qualifiers)` does not return a `Set` equal to the return value of calling `beanManager.getBeans(SomeType.class)` when there are two beans of type `SomeType.class` with no qualifier annotations on them.  I think this is a bug in Weld.

Having said that I will need to refactor this code anyway, as the way that I am acquiring the qualifiers in question is actually kind of dodgy.  I need to do work both with a `ProcessInjectionTarget` event (what I'm doing now) _and_ in various `ProcessBean` events, because other extensions may have programmatically added qualifiers.
